version: '3.8'

services:
  dailypost-api:
    image:  yunusalirony/dailypost-app:latest  # Replace with your actual Docker Hub image
    container_name: billing-post
    restart: unless-stopped
    pull_policy: always
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=uat
      - TZ=UTC
    volumes:
      - /var/daily-post/config/appsettings.uat.json:/app/Config/appsettings.uat.json
      - /var/daily-post/logs:/app/Logs
      - /var/daily-post/message:/app/Message